spring:
  application:
    name: tcf5-health-record-transformer

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:sus_interop}
    username: ${DB_USER:sus_admin}
    password: ${DB_PASS:sus_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true # Útil para o MVP ver o que está acontecendo
    properties:
      hibernate:
        # No Hibernate 6 (Spring Boot 3), o dialeto costuma ser detectado,
        # mas forçar garante suporte ao JSONB
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}  # Porta OUTSIDE do seu Docker
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:tcf5-transformer-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # ADICIONE ISSO: Habilita o cache local para as regras JOLT
  cache:
    type: simple

# Tópicos e configurações da aplicação (podem ser substituídas por valores do Helm/values.yaml)
app:
  kafka:
    inbound-topic: ${KAFKA_INBOUND_TOPIC:atendimentos-brutos}
    dlq-topic: ${KAFKA_DLQ_TOPIC:atendimentos-brutos-dlq}
  # Ativa/desativa validação FHIR (true/false)
  fhir:
    validation:
      enabled: ${APP_FHIR_VALIDATION_ENABLED:false}

# Log para debug (ajuda na defesa da pós)
logging:
  level:
    br.com.tcf5_health_record_transformer: DEBUG
    org.springframework.kafka: INFO

server:
  address: 0.0.0.0
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true