apiVersion: v1
kind: ConfigMap
metadata:
  name: tcf5-health-record-transformer-config
data:
  DB_HOST: "${DB_HOST:-localhost}"
  DB_NAME: "${DB_NAME:-sus_interop}"
  DB_USER: "${DB_USER:-sus_admin}"
  KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BOOTSTRAP_SERVERS:-localhost:29092}"
  KAFKA_CONSUMER_GROUP: "${KAFKA_CONSUMER_GROUP:-tcf5-transformer-group}"
  KAFKA_INBOUND_TOPIC: "${KAFKA_INBOUND_TOPIC:-atendimentos-brutos}"
  KAFKA_DLQ_TOPIC: "${KAFKA_DLQ_TOPIC:-atendimentos-brutos-dlq}"

