apiVersion: v1
kind: Secret
metadata:
  name: tcf5-health-record-transformer-secret
type: Opaque
data:
  # Base64 encode your values before placing here. Example:
  # echo -n 'sus_password' | base64
  DB_PASS: "REPLACE_WITH_BASE64_DB_PASS"

